title: kingcall
author: kingcall
email: kingcall@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  生命不息 奋斗不止
  栽好梧桐树 自有凤凰来

# social links
twitter_username: kingcall
github_username:  kingcall

show_excerpts: true # set to false to remove excerpts on the homepage
theme: monos
